/**
 * Skill type definitions.
 *
 * A skill is a SKILL.md-style instruction pack. It can be installed per agent
 * and injected into the system prompt during dispatch.
 */

export interface SkillCategory {
  id: string
  label: string
}

export type SkillCategoryInput = string | Partial<SkillCategory> | null | undefined

export const DEFAULT_SKILL_CATEGORY: SkillCategory = { id: 'general', label: '通用 / General' }

const CATEGORY_LABELS: Record<string, string> = {
  general: DEFAULT_SKILL_CATEGORY.label,
  coding: '编程 / Coding',
  testing: '测试 / Testing',
  writing: '写作 / Writing',
  research: '研究 / Research',
  planning: '规划 / Planning',
  design: '设计 / Design',
  data: '数据 / Data',
  operations: '运维 / Operations'
}

const CATEGORY_ALIASES: Record<string, string> = {
  general: 'general',
  common: 'general',
  '通用': 'general',
  coding: 'coding',
  code: 'coding',
  review: 'coding',
  refactor: 'coding',
  programming: 'coding',
  '编程': 'coding',
  '代码': 'coding',
  testing: 'testing',
  test: 'testing',
  tests: 'testing',
  qa: 'testing',
  '测试': 'testing',
  writing: 'writing',
  writer: 'writing',
  docs: 'writing',
  documentation: 'writing',
  '写作': 'writing',
  '文档': 'writing',
  research: 'research',
  search: 'research',
  analysis: 'research',
  '研究': 'research',
  '调研': 'research',
  planning: 'planning',
  plan: 'planning',
  architect: 'planning',
  architecture: 'planning',
  '规划': 'planning',
  '架构': 'planning',
  design: 'design',
  ui: 'design',
  ux: 'design',
  '设计': 'design',
  data: 'data',
  analytics: 'data',
  '数据': 'data',
  operations: 'operations',
  ops: 'operations',
  devops: 'operations',
  deploy: 'operations',
  '运维': 'operations',
  '部署': 'operations'
}

export function normalizeSkillCategory(input?: SkillCategoryInput): SkillCategory {
  if (!input) return { ...DEFAULT_SKILL_CATEGORY }
  const rawId = typeof input === 'string' ? input : input.id
  const rawLabel = typeof input === 'string' ? input : input.label
  const idSource = clampCategory(rawId || rawLabel || '', 80)
  const labelSource = clampCategory((typeof input === 'string' ? input : rawLabel) || '', 80)
  const knownId = resolveKnownCategoryId(idSource || labelSource)
  const id = knownId || normalizeCategoryId(idSource) || (labelSource ? `custom-${hashCategory(labelSource)}` : DEFAULT_SKILL_CATEGORY.id)
  return {
    id,
    label: CATEGORY_LABELS[id] || labelSource || id
  }
}

export function inferSkillCategory(values: readonly unknown[]): SkillCategory {
  for (const value of values) {
    const parts = Array.isArray(value) ? value : [value]
    for (const part of parts) {
      const id = resolveKnownCategoryId(String(part || ''))
      if (id && id !== DEFAULT_SKILL_CATEGORY.id) return normalizeSkillCategory({ id })
    }
  }
  return normalizeSkillCategory()
}

function resolveKnownCategoryId(value: string): string {
  const text = value.trim().toLowerCase()
  if (!text) return ''
  const slug = normalizeCategoryId(text)
  if (CATEGORY_ALIASES[text]) return CATEGORY_ALIASES[text]
  if (CATEGORY_ALIASES[slug]) return CATEGORY_ALIASES[slug]
  for (const [alias, id] of Object.entries(CATEGORY_ALIASES)) {
    if (text.includes(alias)) return id
  }
  return ''
}

function normalizeCategoryId(value: string): string {
  return value.trim().toLowerCase().replace(/[^a-z0-9_-]+/gi, '-').replace(/^-+|-+$/g, '').slice(0, 64)
}

function clampCategory(value: unknown, max: number): string {
  return typeof value === 'string' ? value.trim().slice(0, max) : ''
}

function hashCategory(value: string): string {
  let h = 2166136261
  for (let i = 0; i < value.length; i++) {
    h ^= value.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  return (h >>> 0).toString(16)
}

export interface SkillDef {
  id: string
  name: string
  category: SkillCategory
  /** One-line semantic hint used for display and matching. */
  description: string
  /** SKILL.md-style instruction body injected into the system prompt. */
  instructions: string
  tags: string[]
  /** Source marker: builtin / paste / file path. */
  source: string
  createdAt: number
  updatedAt: number
}

/** agentId -> installed skillId list. */
export type SkillInstalls = Record<string, string[]>

export interface SkillInstallState {
  installs: SkillInstalls
}

/** Input for creating/importing skills. id/timestamps are generated by manager. */
export interface SkillInput {
  name: string
  category?: SkillCategoryInput
  description?: string
  instructions: string
  tags?: string[]
  source?: string
}

/** Built-in skill templates. */
export const BUILTIN_SKILLS: SkillInput[] = [
  {
    name: 'Code Reviewer',
    description: '审查代码改动：找正确性 bug、安全风险与可简化/复用点',
    category: { id: 'coding', label: '编程 / Coding' },
    tags: ['builtin', 'review', 'coding'],
    source: 'builtin',
    instructions: [
      'When reviewing code, focus on:',
      '1. Correctness bugs: off-by-one, null/undefined, race conditions, error handling, edge cases.',
      '2. Reuse & simplification: duplicated logic, existing utilities that should be used, dead code.',
      '3. Security: injection, path traversal, secret leakage, unsafe deserialization.',
      'Report findings as a short prioritized list. Cite file:line. Be concrete, no vague praise.'
    ].join('\n')
  },
  {
    name: 'Test Writer',
    description: '为改动补单元测试，覆盖正常、边界和失败路径',
    category: { id: 'testing', label: '测试 / Testing' },
    tags: ['builtin', 'testing', 'coding'],
    source: 'builtin',
    instructions: [
      'When asked to add tests:',
      '1. Match the project\'s existing test framework and file conventions.',
      '2. Cover the happy path, boundary values, and at least one failure/error path.',
      '3. Keep each test focused and independent; avoid shared mutable state.',
      '4. Prefer asserting behavior/outputs over implementation details.'
    ].join('\n')
  },
  {
    name: 'Concise Writer',
    description: '中英技术写作：信息密度高、无套话',
    category: { id: 'writing', label: '写作 / Writing' },
    tags: ['builtin', 'writing'],
    source: 'builtin',
    instructions: [
      'When writing prose or docs:',
      '- Lead with the conclusion, then support it.',
      '- Cut filler, hedging, and generic disclaimers.',
      '- Prefer concrete nouns/verbs and short sentences.',
      '- Keep the user\'s language (zh/en) consistent with their request.'
    ].join('\n')
  },
  {
    name: 'ECC Workflow',
    description: 'Everything Claude Code workflow skill for planning, TDD, review, verification, research, security, and reflection.',
    category: { id: 'planning', label: '规划 / Planning' },
    tags: ['builtin', 'ecc', 'planning', 'testing', 'review', 'verification'],
    source: 'ecc',
    instructions: [
      'Use the Everything Claude Code (ECC) workflow style when it fits the task.',
      '',
      'Core modes:',
      '- /plan: restate the goal, constraints, risks, impact, and verification plan before implementation.',
      '- /tdd: define acceptance criteria, write or identify failing tests first, then implement the smallest useful change.',
      '- /code-review or /review: prioritize correctness bugs, regressions, security risks, and missing tests with file/line evidence.',
      '- /verify: run or describe the relevant checks, report pass/fail results, and name residual risks.',
      '- /research: gather evidence before answering; separate facts, assumptions, and uncertainty.',
      '- /security-review: inspect auth, input validation, path handling, command execution, dependency, and secret risks.',
      '- /reflect: summarize what worked, what failed, reusable lessons, and the next improvement.',
      '',
      'Behavior rules:',
      '- Prefer local repository evidence over memory.',
      '- Keep changes scoped to the user request and existing project patterns.',
      '- Do not claim verification passed unless checks actually ran.',
      '- When a slash command is present, treat it as the active ECC mode for that turn.'
    ].join('\n')
  }
]
